#!/usr/bin/env zsh
#*****************************************************************************************
# cancel_awake
#
# his command will cancel the computer's "stay awake" mode
#
# Author   :  Gary Ash <gary.ash@icloud.com>
# Created  :   1-May-2025  3:22pm
# Modified :
#
# Copyright © 2024 By Gary Ash All rights reserved.
#*****************************************************************************************
cancel_awake() {
	if [[ -n $ZSH_VERSION ]]; then
		setopt local_options no_monitor
	fi

	kill $CAFFEINATE
	wait
	unset CAFFEINATE

	if [[ -n $ZSH_VERSION ]]; then
		setopt monitor
	fi
}
cancel_awake
