#!/usr/bin/env zsh
#*****************************************************************************************
# mkd
#
# Make the directory/directory structure named on the command line and enter it
#
# Author   :  Gary Ash <gary.ash@icloud.com>
# Created  :   9-Dec-2024 10:04pm
# Modified :
#
# Copyright © 2024 By Gary Ash All rights reserved.
#*****************************************************************************************
mkdir -p "$@"
cd "$_" || return
