#!/usr/bin/env zsh
#*****************************************************************************************
# reset-launchpad
#
# Reset the macOS launch pad
#
# Author   :  Gary Ash <gary.ash@icloud.com>
# Created  :  17-May-2025  9:57pm
# Modified :
#
# Copyright © 2024 By Gary Ash All rights reserved.
#*****************************************************************************************
defaults write com.apple.dock ResetLaunchPad -bool true
killall Dock
